services:
  app:
    restart: unless-stopped
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${SERVICE_PORT}
    depends_on:
      - db
    ports:
      - "22231:${SERVICE_PORT}"
      - "80:${SERVICE_PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  db:
    restart: unless-stopped
    container_name: db
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: